var $LINKS_COMPRAR=[];
$(function(){function n(b,a){$(a+" .btn-voltar-home").on("click",function(){g("");$(a).fadeOut();$(b).fadeIn();$(b.replace("btn-","")).animate({"margin-left":p},500,function(){for(key in k)key!=b&&$(key.replace("btn-","")).fadeIn()});$(a+" .btn-voltar-home").off("click");for(key in e[a])$(a+" "+key).off("mouseenter"),$(a+" "+key+"-hover").off("mouseenter").off("mouseleave").off("click"),l([key,key+"-hover"]);$("#top-menu").fadeOut();$.each(q,function(a){$("#top-menu "+a).off("click");target_descarrega=
target_carrega=""});r(a,c);h=c=""});$.each(e[a],function(b,d){$(a+" "+b).css({opacity:0.5});""==c&&($(a+" "+b).css({opacity:1}),$(a+" #btn-seta").css({top:parseFloat($(a+" "+b).css("height"))/3+parseFloat($(a+" "+b).position().top)+9+"px"}).fadeIn(),$(a+" "+d[0]).fadeIn(500),"true"==d[1]&&s(a,d[0]),t(a,d[3]),f=d[3],g(h+"/"+f),c=b);$(a+" "+b).on("mouseenter",function(){for(key in e[a])$(a+" "+key).show(),$(a+" "+key+"-hover").hide();$(a+" "+b).hide();$(a+" "+b+"-hover").show()});$(a+" "+b+"-hover").on("mouseenter",
function(){$(a+" .submenu #btn-label p").html(d[2]);$(a+" .submenu #btn-label").stop(!0,!0).fadeOut(200).css({top:parseFloat($(a+" "+b+"-hover").css("height"))/3+parseFloat($(a+" "+b+"-hover").position().top)+"px"}).fadeIn(200)}).on("mouseleave",function(){$(a+" "+b).show();$(a+" "+b+"-hover").hide();$(a+" .submenu #btn-label p").html("");$(a+" .submenu #btn-label").stop(!0,!0).fadeIn(200).fadeOut(200)}).on("click",function(){""!=c&&r(a,c);$(a+" "+b).css({opacity:1});$(a+" #btn-seta").css({top:parseFloat($(a+
" "+b+"-hover").css("height"))/3+parseFloat($(a+" "+b+"-hover").position().top)+9+"px"});$(a+" "+d[0]).fadeIn(400);"true"==d[1]&&s(a,d[0]);t(a,d[3]);f=d[3];g(h+"/"+f);c=b})});$("#top-menu").fadeIn();$.each(q,function(b,d){if(b=="#btn-"+a.replace("#",""))$("#top-menu "+b).css({display:"none"});else $("#top-menu "+b).css({display:"block"}).on("click",function(b){b.preventDefault();var c=$(d);$(a+" .btn-voltar-home").click();var e=setInterval(function(){c.click();clearInterval(e)},1E3)})})}function r(b){$(b+
" "+c).css({opacity:0.5});try{if($(b+" "+e[b][c][0]).css({display:"none"}),l(b+" "+e[b][c][0]),"true"==e[b][c][1]){var a=e[b][c][0];$.each(j,function(d){$(b+" "+a+" "+d).off("mouseenter").off("mouseleave");l(b+" "+a+" "+d)});m=""}}catch(y){}f=""}function t(b,a){$("#btn-comprar-"+b.replace("#","")).parents("a").attr("href",w["link_"+b.replace("#","")+"_"+a]);$("#btn-comprar-"+b.replace("#","")).parents("a").off("click").on("click",function(){g(b.replace("#","")+"/"+a+"/comprar")})}function s(b,a){$.each(j,
function(c,d){$(b+" "+a+" "+c).css({opacity:0.5}).on("mouseenter",function(e){for(key in j)key!=c&&$(b+" "+a+" "+key).css({"z-index":0});$(b+" "+a+" "+c).css({opacity:1});$(b+" "+a+" "+d[0]).stop(!0,!0).fadeOut().fadeIn();u=e.timeStamp}).on("mouseleave",function(e){for(key in j)key!=c&&$(b+" "+a+" "+key).css({"z-index":4});$(b+" "+a+" "+c).css({opacity:0.5});$(b+" "+a+" "+d[0]).stop(!0,!0).fadeIn().fadeOut();v=e.timeStamp;v-u>x&&(m=d[1],g(h+"/"+f+"/"+m))})})}function l(b){if($.isArray(b))for(var a=
0;a<b.length;a++)$(b[a]).removeAttr("style");else $(b).removeAttr("style")}function g(b){""!=b?_gaq.push(["_trackPageview",window.location.pathname+b+".html"]):_gaq.push(["_trackPageview",window.location.pathname])}var q={"#btn-cozinha":"#btn-home-cozinha","#btn-alimentos":"#btn-home-alimentos","#btn-lavanderia":"#btn-home-lavanderia"},k={"#btn-home-cozinha":["#cozinha","cozinha"],"#btn-home-alimentos":["#alimentos","alimentos"],"#btn-home-lavanderia":["#lavanderia","lavanderia"]},p=0,e={"#cozinha":{"#btn-01":["#conteudo-01",
"true","Utens\u00edlios de Silicone","utensilios_silicone"],"#btn-02":["#conteudo-02","true","Formas de S\u00edlicone","formas_silicone"],"#btn-03":["#conteudo-03","true","Formas Jump","formas_jump"],"#btn-04":["#conteudo-04","false","Panela a Vapor Para Micro-ondas","panela_vapor_microondas_silicone"],"#btn-05":["#conteudo-05","false","Panela Para Micro-ondas","panela_microondas"],"#btn-06":["#conteudo-06","false","Panela a Vapor Para Micro-ondas","panela_vapor_microondas"],"#btn-07":["#conteudo-07",
"true","Organizadores de Geladeira","organizadores_geladeira"]},"#alimentos":{"#btn-01":["#conteudo-01","true","Potes Linha Conserva F\u00e1cil","potes_conserva_facil"],"#btn-02":["#conteudo-02","false","Tampa F\u00e1cil Dome","tampa_facil_dome"],"#btn-03":["#conteudo-03","true","Saquinhos Conserva F\u00e1cil","saquinhos_conserva_facil"],"#btn-04":["#conteudo-04","true","Guarda F\u00e1cil","guarda_facil"],"#btn-05":["#conteudo-05","false","Tampa F\u00e1cil","tampa_facil"]},"#lavanderia":{"#btn-01":["#conteudo-01",
"false","Capas de M\u00e1quina de Lavar","capas_maquina_lavar"],"#btn-02":["#conteudo-02","true","Sacos de Roupa \u00cdntima","sacos_roupa_intima"],"#btn-03":["#conteudo-03","false","Grade para Secadora Brastemp","grade_secadora_brastemp"],"#btn-04":["#conteudo-04","false","Brastemp BAG","brastemp_bag"]}},c="",j={"#spot-01":["#conteudo-spot-01","spot1"],"#spot-02":["#conteudo-spot-02","spot2"],"#spot-03":["#conteudo-spot-03","spot3"],"#spot-04":["#conteudo-spot-04","spot4"],"#spot-05":["#conteudo-spot-05",
"spot5"]},x=1E3,u=0,v=0,h="",f="",m="",w={link_cozinha_utensilios_silicone:$LINKS_COMPRAR[0],link_cozinha_formas_silicone:$LINKS_COMPRAR[1],link_cozinha_formas_jump:$LINKS_COMPRAR[2],link_cozinha_panela_vapor_microondas_silicone:$LINKS_COMPRAR[3],link_cozinha_panela_microondas:$LINKS_COMPRAR[4],link_cozinha_panela_vapor_microondas:$LINKS_COMPRAR[5],link_cozinha_organizadores_geladeira:$LINKS_COMPRAR[6],link_alimentos_potes_conserva_facil:$LINKS_COMPRAR[7],link_alimentos_tampa_facil_dome:$LINKS_COMPRAR[8],
link_alimentos_saquinhos_conserva_facil:$LINKS_COMPRAR[9],link_alimentos_guarda_facil:$LINKS_COMPRAR[10],link_alimentos_tampa_facil:$LINKS_COMPRAR[11],link_lavanderia_capas_maquina_lavar:$LINKS_COMPRAR[12],link_lavanderia_sacos_roupa_intima:$LINKS_COMPRAR[13],link_lavanderia_grade_secadora_brastemp:$LINKS_COMPRAR[14],link_lavanderia_brastemp_bag:$LINKS_COMPRAR[15]};$.each(k,function(b,a){$(b).on("click",function(){$(b).fadeOut();for(key in k)key!=b?$(key.replace("btn-","")).fadeOut():(p=$(key.replace("btn-",
"")).css("margin-left"),"#btn-home-cozinha"!=key?$(key.replace("btn-","")).delay(400).animate({"margin-left":"-480px"},500,function(){$(a[0]).fadeIn();n(b,a[0])}):$(key.replace("btn-","")).delay(400).animate({"margin-left":"-480px"},0,function(){$(a[0]).fadeIn();n(b,a[0])}),h=a[1])})})});